### ISSUE TITLE
Cant Migrate Spells/Fight Techniques -- Kann keine Spells/Sonderfertigkeiten migrieren

### ISSUE THREAD

**Issue by izu23** [Plushtoast/dsa5-foundryVTT#409]
Hi,
wenn ich Zauber/Kampftechniken oder Sonderfertigkeiten migrieren möchte bekomme ich bei alle Charakteren folgende Meldung:

Error: The provided Item type must be in the array of types defined by the game system
    at ItemData._validateField (file:///home/ec2-user/foundryvtt/resources/app/common/abstract/data.mjs:376:13)
    at ItemData.validate (file:///home/ec2-user/foundryvtt/resources/app/common/abstract/data.mjs:267:14)
    at new DocumentData (file:///home/ec2-user/foundryvtt/resources/app/common/abstract/data.mjs:48:10)
    at new ItemData (file:///home/ec2-user/foundryvtt/resources/app/common/data/data.mjs:789:1)
    at new Document (file:///home/ec2-user/foundryvtt/resources/app/common/abstract/document.mjs:46:14)
    at new BaseItem (file:///home/ec2-user/foundryvtt/resources/app/common/documents.mjs:501:1)
    at new <anonymous> (file:///home/ec2-user/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:246)
    at new Item (file:///home/ec2-user/foundryvtt/resources/app/dist/database/documents/item.mjs:1:232)
    at new <anonymous> (file:///home/ec2-user/foundryvtt/resources/app/dist/database/backend/server-compendium.mjs:1:143)
    at new o (file:///home/ec2-user/foundryvtt/resources/app/dist/database/database.mjs:1:2120)

Version 2.0.1 mit Foundry 8.6

**Comment by Plushtoast** [comment]
Deine Welt wurde nicht richtig geladen.
Höchstwahrscheinlich liegt das an einem imkompatiblen Modul --> alles deaktivieren.
Die Version 2.0.1 gibt es noch nicht.

Außerdem sind die DSA Module noch nicht kompatibel. Sie liegen dem Foundry Staff bereits vor. Der Umzug auf die neue Version ist aber mit erheblichem Aufwand verbunden und deswegen haben die da noch keine Zeit gehabt.

Geduld...

**Comment by Plushtoast** [comment]
Deine Welt wurde nicht richtig geladen.
Höchstwahrscheinlich liegt das an einem imkompatiblen Modul --> alles deaktivieren.
Die Version 2.0.1 gibt es noch nicht.

Außerdem sind die DSA Module noch nicht kompatibel. Sie liegen dem Foundry Staff bereits vor. Der Umzug auf die neue Version ist aber mit erheblichem Aufwand verbunden und deswegen haben die da noch keine Zeit gehabt.

Geduld...

Die Warnung mit den Kompatibilitätsproblemen muss man derzeit ernst nehmen...

**Comment by Plushtoast** [comment]
Bitte nochmal mit den aktualisierten Modulen und System versuchen bei deaktivierten Modulen von Dritten und Feedback geben.

**Comment by izu23** [comment]
Hi, mit den aktuellen modulen funktioniert es ohne Probleme. Nach ein wenig trial and error hab ich rausgefunden das es an dem Modul "Dynamic Effects using Active Effects" liegt. Es scheint in diesem Zusammenhang leider nicht kompatibel zu sein.
Danke für die schnelle Antwort.
